### ISSUE TITLE
samba disappeared from nf-core ?

### ISSUE THREAD

**Issue by adefewings** [ifremer-bioinformatics/samba#1]
Upon following the instructions, it seems that samba has disappeared from the nextflow core, is that correct? 

$ nextflow run nf-core/samba -profile test,singularity
N E X T F L O W  ~  version 20.10.0
Pulling nf-core/samba ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/samba/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nf-core/samba/contents/main.nf

Is there a proposed alternative?

**Comment by pgdurand** [comment]
Hi,
yes, we are currently updating Samba and you pointed out a possible bug... we'll fixing that soon and we'll let you know as soon as fix is done.
Patrick

**Comment by cnoel-sebimer** [comment]
A new version (v.3.0.0) has just been released. The documentation for downloading and using SAMBA has been updated.

**Comment by adefewings** [comment]
Excellent news, thank you.  One further question, if I may, is there a neat way to handle the situation where the compute nodes of a cluster cannot get to the internet themselves to download the [Singularity] images needed?

**Comment by cnoel-sebimer** [comment]
Yes, the solution is to provide a centralised caching directory by setting the NXF_SINGULARITY_CACHEDIR variable with the path of this directory containing previously downloaded images. This centralised caching directory can contain all the singularity images of nextflow workflows available on the cluster, not just the SAMBA one.

**Comment by adefewings** [comment]
Many thanks for your help thus far.  I feel like I'm nearly there in getting the shortreads test case running on our internal-only compute via a few necessary steps:
1. Supplying the data in advance in tax.databases.test and training_databases centrally.
2. Re-writing paths in the training_data to match where our end-users have it.
3. Found that specifying NXF_SINGULARITY_CACHEDIR as a centralised non-user-writable location produced a java error (FileNotFoundException) with one of the singularity images that I worked round by populating a user-owned (writable) directory with symlinks to the central dir and setting NXF_SINGULARITY_CACHEDIR appropriately.

But now I'm a bit confused as running the shortreads test proceeds ok until it throws this error during 'mirdecon':
```
executor >  local (7)
[6b/6359dc] process > get_test_data          [100%] 1 of 1 ✔
[0c/dcd805] process > data_integrity         [100%] 1 of 1 ✔
[8d/ac711d] process > q2_import              [100%] 1 of 1 ✔
[ad/86ccb4] process > q2_cutadapt            [100%] 1 of 1 ✔
[78/388d7c] process > q2_dada2               [100%] 1 of 1 ✔
[ff/c9b4a1] process > q2_dbotu3              [100%] 1 of 1 ✔
[82/9d61dd] process > q2_taxonomy            [100%] 1 of 1 ✔
[-        ] process > microDecon_step1       -
[-        ] process > microDecon_step2       -
[-        ] process > microDecon_step3       -
[-        ] process > microDecon_step4       -
[-        ] process > q2_phylogeny           -
[-        ] process > q2_picrust2_analysis   -
[-        ] process > q2_picrust2_stats      -
[-        ] process > q2_ancom               -
[-        ] process > prepare_data_for_stats -
[-        ] process > stats_alpha            -
[-        ] process > stats_beta             -
[-        ] process > stats_beta_rarefied    -
[-        ] process > stats_beta_deseq2      -
[-        ] process > stats_beta_css         -
[-        ] process > stats_desc_comp        -
[-        ] process > report                 -
[-        ] process > compress_result        -
Pulling Singularity image docker://sebimer/samba-microdecon:1.0.2 [cache /scratch/b.iss03c/samba/samba-3.0.0/singularity_images/sebimer-samba-microdecon-1.0.2.img]
Error executing process > 'microDecon_step1'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name sebimer-samba-microdecon-1.0.2.img.pulling.1613142789895 docker://sebimer/samba-microdecon:1.0.2 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://sebimer/samba-microdecon:1.0.2: error pinging docker registry registry-1.docker.io: Get https://registry-1.docker.io/v2/: dial tcp 107.23.149.57:443: connect: network is unreachable
-[samba workflow] Pipeline completed with errors-
```
...which looks to me to be a bit odd as the singularity image is present in the cache and is used by a manual re-creation of the pull:
```
 > singularity pull  --name sebimer-samba-microdecon-1.0.2.img.pulling.1613142789895 docker://sebimer/samba-microdecon:1.0.2
INFO:    Using cached SIF image
```
Apologies for having yet more issues......compute node internet access would be nice indeed.

**Comment by cnoel-sebimer** [comment]
Our cluster also has compute nodes without internet access but we don't have any trouble with a singularity pull error. May I suggest you check the following points : 

1) in your singularity cache dir, can you check that you have 7 different singularity samba images :
sebimer-samba-biopython-1.78.img
sebimer-samba-jinja2-2.11.1.img
sebimer-samba-longreads-1.0.img
sebimer-samba-microdecon-1.0.2.img
sebimer-samba-qiime2-2019.10.img
sebimer-samba-r-3.6.1.img
sebimer-samba-seqtk-1.2.img

2) in any case, delete every \*microdecon\*.img that you have in this directory

3) Get a new copy of the microDecon singularity image : `singularity pull --name samba-microdecon_1.0.2.img docker://sebimer/samba-microdecon:1.0.2`

4) Test your microDecon image : 
`singularity exec samba-microdecon_1.0.2.img R`
`library(microDecon)`

You should not have any errors at step 4. If true, go ahead and try again the SAMBA pipeline

**Comment by cnoel-sebimer** [comment]
Error resolved
